version: '3.1'
services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@sswi0rd
    ports:
      - "3306:3306"
volumes:
  mysql_data:
    driver: local